apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: app3:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred