apiVersion: apps/v1
kind: Deployment
metadata:
  name: noredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noredis
  template:
    metadata:
      labels:
        app: noredis
    spec:
      containers:
        - name: noredis
          image: noredis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: noredis-service
spec:
  selector:
    app: noredis
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30004
  type: NodePort
